[package]
name = "rusht"
version = "0.1.0"
edition = "2021"

[lib]
name = "rusht"
path = "src/lib.rs"

[[bin]]
name = "merge_ignores"
path = "src/merge_ignores/main.rs"

[dependencies]
bump_alloc = "0.1.0"
fd-find = "8.3.1"
tokio = { version = "1.17.0", features = ["full"] }

