[package]
name = "rusht"
description = "Shell commands written in Rust"
version = "1.0.0"
edition = "2021"
authors = ["Mark <mverleg.noreply@gmail.com>"]
homepage = "https://github.com/mverleg/rusht"
license = "BSD-3-Clause"
publish = true

[lib]
name = "rusht"
path = "src/lib.rs"

[[bin]]
name = "cmadd"
path = "src/cmd/main_add.rs"

[[bin]]
name = "cmdo"
path = "src/cmd/main_do.rs"

[[bin]]
name = "cmlist"
path = "src/cmd/main_list.rs"

[[bin]]
name = "cmdrop"
path = "src/cmd/main_drop.rs"

[[bin]]
name = "cached"
path = "src/cached/main_cached.rs"

[[bin]]
name = "unique"
path = "src/filter/main_unique.rs"

[[bin]]
name = "grab"
path = "src/filter/main_grab.rs"

[[bin]]
name = "dir_with"
path = "src/find/main_dir_with.rs"

[[bin]]
name = "locked"
path = "src/wait/main_locked.rs"

[[bin]]
name = "rusht"
path = "src/main_all.rs"

[dependencies]
#structopt = "*"
clap = { version = "3.0", default-features = true, features = ["std", "derive", "unicode"] }
#walkdir = "*"
lazy_static = "*"
regex = { version = "*", default-features = false, features = ["std"] }
itertools = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
chrono = { version = "*", features = ["std", "clock", "serde"] }
#strum = "*"
#strum_macros = "*"
dirs = "*"
log = "*"
env_logger = "*"
memoize = "*"
rand = "*"
ustr = "*"
parse_duration = "*"
smallvec = "*"
sha2 = "*"
base64 = "*"
rayon = "*"
dashmap = "*"

[dev-dependencies]
tempfile = "*"

[profile.release]
opt-level = 'z'     # Optimize for size.
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
panic = 'abort'     # Abort on panic
strip = true        # Strip symbols from binary*

