[package]
name = "rusht"
version = "0.1.0"
edition = "2021"
publish = false

#[[bin]]
#name = "logcount"
#path = "src/log_stats.rs"

[lib]
name = "rusht"
path = "src/lib.rs"

[[bin]]
name = "cmadd"
path = "src/cmd/main_add.rs"

[[bin]]
name = "cmdo"
path = "src/cmd/main_do.rs"

[[bin]]
name = "cmlist"
path = "src/cmd/main_list.rs"

[[bin]]
name = "cmdrop"
path = "src/cmd/main_drop.rs"

[[bin]]
name = "cached"
path = "src/cached/main_cached.rs"

[[bin]]
name = "unique"
path = "src/filter/main_unique.rs"

[[bin]]
name = "dir_with"
path = "src/find/main_dir_with.rs"

[dependencies]
#structopt = "*"
clap = { version = "3.0", default-features = true, features = ["std", "derive", "unicode"] }
#walkdir = "*"
lazy_static = "*"
regex = { version = "*", default-features = false, features = ["std"] }
itertools = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
chrono = { version = "*", features = ["std", "clock", "serde"] }
#strum = "*"
#strum_macros = "*"
dirs = "*"
log = "*"
env_logger = "*"
memoize = "*"
rand = "*"
ustr = "*"
parse_duration = "*"
smallvec = "*"
sha2 = "*"
base64 = "*"
rayon = "*"
dashmap = "*"

[dev-dependencies]
tempfile = "*"

[profile.release]
opt-level = 'z'     # Optimize for size.
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
panic = 'abort'     # Abort on panic
strip = true        # Strip symbols from binary*

